//
// Code generated DO NOT EDIT.
//
// Generated in el/element.go:11 using elements.txt
package el

// A constructs a veun representation of the a html element.
//
// This function is autogenerated.
func A() *Element {
  return &Element{tag:"a"}
}

// Area constructs a veun representation of the area html element.
//
// This function is autogenerated.
func Area() *Element {
  return &Element{tag:"area"}
}

// Article constructs a veun representation of the article html element.
//
// This function is autogenerated.
func Article() *Element {
  return &Element{tag:"article"}
}

// Aside constructs a veun representation of the aside html element.
//
// This function is autogenerated.
func Aside() *Element {
  return &Element{tag:"aside"}
}

// Base constructs a veun representation of the base html element.
//
// This function is autogenerated.
func Base() *Element {
  return &Element{tag:"base"}
}

// Body constructs a veun representation of the body html element.
//
// This function is autogenerated.
func Body() *Element {
  return &Element{tag:"body"}
}

// Br constructs a veun representation of the br html element.
//
// This function is autogenerated.
func Br() *Element {
  return &Element{tag:"br"}
}

// Caption constructs a veun representation of the caption html element.
//
// This function is autogenerated.
func Caption() *Element {
  return &Element{tag:"caption"}
}

// Code constructs a veun representation of the code html element.
//
// This function is autogenerated.
func Code() *Element {
  return &Element{tag:"code"}
}

// Dd constructs a veun representation of the dd html element.
//
// This function is autogenerated.
func Dd() *Element {
  return &Element{tag:"dd"}
}

// Details constructs a veun representation of the details html element.
//
// This function is autogenerated.
func Details() *Element {
  return &Element{tag:"details"}
}

// Div constructs a veun representation of the div html element.
//
// This function is autogenerated.
func Div() *Element {
  return &Element{tag:"div"}
}

// Dl constructs a veun representation of the dl html element.
//
// This function is autogenerated.
func Dl() *Element {
  return &Element{tag:"dl"}
}

// Dt constructs a veun representation of the dt html element.
//
// This function is autogenerated.
func Dt() *Element {
  return &Element{tag:"dt"}
}

// Em constructs a veun representation of the em html element.
//
// This function is autogenerated.
func Em() *Element {
  return &Element{tag:"em"}
}

// Embed constructs a veun representation of the embed html element.
//
// This function is autogenerated.
func Embed() *Element {
  return &Element{tag:"embed"}
}

// H1 constructs a veun representation of the h1 html element.
//
// This function is autogenerated.
func H1() *Element {
  return &Element{tag:"h1"}
}

// H2 constructs a veun representation of the h2 html element.
//
// This function is autogenerated.
func H2() *Element {
  return &Element{tag:"h2"}
}

// H3 constructs a veun representation of the h3 html element.
//
// This function is autogenerated.
func H3() *Element {
  return &Element{tag:"h3"}
}

// H4 constructs a veun representation of the h4 html element.
//
// This function is autogenerated.
func H4() *Element {
  return &Element{tag:"h4"}
}

// H5 constructs a veun representation of the h5 html element.
//
// This function is autogenerated.
func H5() *Element {
  return &Element{tag:"h5"}
}

// H6 constructs a veun representation of the h6 html element.
//
// This function is autogenerated.
func H6() *Element {
  return &Element{tag:"h6"}
}

// HTML constructs a veun representation of the html html element.
//
// This function is autogenerated.
func HTML() *Element {
  return &Element{tag:"html"}
}

// Head constructs a veun representation of the head html element.
//
// This function is autogenerated.
func Head() *Element {
  return &Element{tag:"head"}
}

// Hr constructs a veun representation of the hr html element.
//
// This function is autogenerated.
func Hr() *Element {
  return &Element{tag:"hr"}
}

// Img constructs a veun representation of the img html element.
//
// This function is autogenerated.
func Img() *Element {
  return &Element{tag:"img"}
}

// Input constructs a veun representation of the input html element.
//
// This function is autogenerated.
func Input() *Element {
  return &Element{tag:"input"}
}

// Meta constructs a veun representation of the meta html element.
//
// This function is autogenerated.
func Meta() *Element {
  return &Element{tag:"meta"}
}

// Nav constructs a veun representation of the nav html element.
//
// This function is autogenerated.
func Nav() *Element {
  return &Element{tag:"nav"}
}

// Li constructs a veun representation of the li html element.
//
// This function is autogenerated.
func Li() *Element {
  return &Element{tag:"li"}
}

// Link constructs a veun representation of the link html element.
//
// This function is autogenerated.
func Link() *Element {
  return &Element{tag:"link"}
}

// Ol constructs a veun representation of the ol html element.
//
// This function is autogenerated.
func Ol() *Element {
  return &Element{tag:"ol"}
}

// P constructs a veun representation of the p html element.
//
// This function is autogenerated.
func P() *Element {
  return &Element{tag:"p"}
}

// Picture constructs a veun representation of the picture html element.
//
// This function is autogenerated.
func Picture() *Element {
  return &Element{tag:"picture"}
}

// Pre constructs a veun representation of the pre html element.
//
// This function is autogenerated.
func Pre() *Element {
  return &Element{tag:"pre"}
}

// Script constructs a veun representation of the script html element.
//
// This function is autogenerated.
func Script() *Element {
  return &Element{tag:"script"}
}

// Section constructs a veun representation of the section html element.
//
// This function is autogenerated.
func Section() *Element {
  return &Element{tag:"section"}
}

// Source constructs a veun representation of the source html element.
//
// This function is autogenerated.
func Source() *Element {
  return &Element{tag:"source"}
}

// Span constructs a veun representation of the span html element.
//
// This function is autogenerated.
func Span() *Element {
  return &Element{tag:"span"}
}

// Strong constructs a veun representation of the strong html element.
//
// This function is autogenerated.
func Strong() *Element {
  return &Element{tag:"strong"}
}

// Style constructs a veun representation of the style html element.
//
// This function is autogenerated.
func Style() *Element {
  return &Element{tag:"style"}
}

// Summary constructs a veun representation of the summary html element.
//
// This function is autogenerated.
func Summary() *Element {
  return &Element{tag:"summary"}
}

// TBody constructs a veun representation of the tbody html element.
//
// This function is autogenerated.
func TBody() *Element {
  return &Element{tag:"tbody"}
}

// TFoot constructs a veun representation of the tfoot html element.
//
// This function is autogenerated.
func TFoot() *Element {
  return &Element{tag:"tfoot"}
}

// THead constructs a veun representation of the thead html element.
//
// This function is autogenerated.
func THead() *Element {
  return &Element{tag:"thead"}
}

// Table constructs a veun representation of the table html element.
//
// This function is autogenerated.
func Table() *Element {
  return &Element{tag:"table"}
}

// Td constructs a veun representation of the td html element.
//
// This function is autogenerated.
func Td() *Element {
  return &Element{tag:"td"}
}

// Th constructs a veun representation of the th html element.
//
// This function is autogenerated.
func Th() *Element {
  return &Element{tag:"th"}
}

// Tr constructs a veun representation of the tr html element.
//
// This function is autogenerated.
func Tr() *Element {
  return &Element{tag:"tr"}
}

// Ul constructs a veun representation of the ul html element.
//
// This function is autogenerated.
func Ul() *Element {
  return &Element{tag:"ul"}
}
