package html

import "github.com/stanistan/veun"

//
//
// This file is generated by ./generate-elements using elements.txt!
//
//


// A constructs a veun representation of a a.
//
// This function is autogenerated.
func A(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("a", attrs, veun.Views(content))
}

// Article constructs a veun representation of a article.
//
// This function is autogenerated.
func Article(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("article", attrs, veun.Views(content))
}

// Aside constructs a veun representation of a aside.
//
// This function is autogenerated.
func Aside(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("aside", attrs, veun.Views(content))
}

// Body constructs a veun representation of a body.
//
// This function is autogenerated.
func Body(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("body", attrs, veun.Views(content))
}

// Caption constructs a veun representation of a caption.
//
// This function is autogenerated.
func Caption(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("caption", attrs, veun.Views(content))
}

// Code constructs a veun representation of a code.
//
// This function is autogenerated.
func Code(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("code", attrs, veun.Views(content))
}

// Dd constructs a veun representation of a dd.
//
// This function is autogenerated.
func Dd(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("dd", attrs, veun.Views(content))
}

// Details constructs a veun representation of a details.
//
// This function is autogenerated.
func Details(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("details", attrs, veun.Views(content))
}

// Div constructs a veun representation of a div.
//
// This function is autogenerated.
func Div(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("div", attrs, veun.Views(content))
}

// Dl constructs a veun representation of a dl.
//
// This function is autogenerated.
func Dl(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("dl", attrs, veun.Views(content))
}

// Dt constructs a veun representation of a dt.
//
// This function is autogenerated.
func Dt(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("dt", attrs, veun.Views(content))
}

// Em constructs a veun representation of a em.
//
// This function is autogenerated.
func Em(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("em", attrs, veun.Views(content))
}

// H1 constructs a veun representation of a h1.
//
// This function is autogenerated.
func H1(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("h1", attrs, veun.Views(content))
}

// H2 constructs a veun representation of a h2.
//
// This function is autogenerated.
func H2(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("h2", attrs, veun.Views(content))
}

// H3 constructs a veun representation of a h3.
//
// This function is autogenerated.
func H3(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("h3", attrs, veun.Views(content))
}

// H4 constructs a veun representation of a h4.
//
// This function is autogenerated.
func H4(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("h4", attrs, veun.Views(content))
}

// H5 constructs a veun representation of a h5.
//
// This function is autogenerated.
func H5(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("h5", attrs, veun.Views(content))
}

// H6 constructs a veun representation of a h6.
//
// This function is autogenerated.
func H6(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("h6", attrs, veun.Views(content))
}

// HTML constructs a veun representation of a html.
//
// This function is autogenerated.
func HTML(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("html", attrs, veun.Views(content))
}

// Head constructs a veun representation of a head.
//
// This function is autogenerated.
func Head(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("head", attrs, veun.Views(content))
}

// Img constructs a veun representation of a img.
//
// This function is autogenerated.
func Img(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("img", attrs, veun.Views(content))
}

// Li constructs a veun representation of a li.
//
// This function is autogenerated.
func Li(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("li", attrs, veun.Views(content))
}

// Link constructs a veun representation of a link.
//
// This function is autogenerated.
func Link(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("link", attrs, veun.Views(content))
}

// Ol constructs a veun representation of a ol.
//
// This function is autogenerated.
func Ol(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("ol", attrs, veun.Views(content))
}

// P constructs a veun representation of a p.
//
// This function is autogenerated.
func P(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("p", attrs, veun.Views(content))
}

// Picture constructs a veun representation of a picture.
//
// This function is autogenerated.
func Picture(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("picture", attrs, veun.Views(content))
}

// Pre constructs a veun representation of a pre.
//
// This function is autogenerated.
func Pre(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("pre", attrs, veun.Views(content))
}

// Script constructs a veun representation of a script.
//
// This function is autogenerated.
func Script(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("script", attrs, veun.Views(content))
}

// Section constructs a veun representation of a section.
//
// This function is autogenerated.
func Section(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("section", attrs, veun.Views(content))
}

// Span constructs a veun representation of a span.
//
// This function is autogenerated.
func Span(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("span", attrs, veun.Views(content))
}

// Strong constructs a veun representation of a strong.
//
// This function is autogenerated.
func Strong(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("strong", attrs, veun.Views(content))
}

// Style constructs a veun representation of a style.
//
// This function is autogenerated.
func Style(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("style", attrs, veun.Views(content))
}

// Summary constructs a veun representation of a summary.
//
// This function is autogenerated.
func Summary(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("summary", attrs, veun.Views(content))
}

// TBody constructs a veun representation of a tbody.
//
// This function is autogenerated.
func TBody(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("tbody", attrs, veun.Views(content))
}

// TFoot constructs a veun representation of a tfoot.
//
// This function is autogenerated.
func TFoot(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("tfoot", attrs, veun.Views(content))
}

// THead constructs a veun representation of a thead.
//
// This function is autogenerated.
func THead(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("thead", attrs, veun.Views(content))
}

// Table constructs a veun representation of a table.
//
// This function is autogenerated.
func Table(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("table", attrs, veun.Views(content))
}

// Td constructs a veun representation of a td.
//
// This function is autogenerated.
func Td(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("td", attrs, veun.Views(content))
}

// Th constructs a veun representation of a th.
//
// This function is autogenerated.
func Th(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("th", attrs, veun.Views(content))
}

// Tr constructs a veun representation of a tr.
//
// This function is autogenerated.
func Tr(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("tr", attrs, veun.Views(content))
}

// Ul constructs a veun representation of a ul.
//
// This function is autogenerated.
func Ul(attrs Attrs, content ...veun.AsView) veun.AsView {
  return El("ul", attrs, veun.Views(content))
}
